project_name: drprune
env:
  - GO111MODULE=on
before:
  hooks:
    - make clean
    - go mod tidy
    - go generate ./...
builds:
  - id: drprune
    binary: drprune
    env:
      - CGO_ENABLED=0
    main: ./cmd/drprune/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - ppc64le
    mod_timestamp: "{{.CommitTimestamp}}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X "github.com/lpmatos/drprune/internal/version.builtDate={{.CommitDate}}"
      - -X "github.com/lpmatos/drprune/internal/version.builtBy=goreleaser"
      - -X "github.com/lpmatos/drprune/internal/version.cliVersion={{.Env.CLIENT_VERSION}}"
      - -X "github.com/lpmatos/drprune/internal/version.commit={{.Commit}}"
      - -X "github.com/lpmatos/drprune/internal/version.commitShort={{.ShortCommit}}"
      - -X "github.com/lpmatos/drprune/internal/version.commitBranch={{.Env.GIT_BRANCH}}"
      - -X "github.com/lpmatos/drprune/internal/version.goVersion={{.Env.GO_VERSION}}"
archives:
  - name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
snapshot:
  name_template: "SNAPSHOT-{{ .Commit }}"
checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"
  algorithm: sha256
changelog:
  skip: true
brews:
  - name: drprune
    tap:
      owner: ci-monk
      branch: main
      name: homebrew-tools
    folder: formula
    commit_author:
      name: ci-monk
      email: ci-monk@protonmail.com
    commit_msg_template: "feat: brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/ci-monk/drprune"
    description: "Prune old images on GitHub (ghcr.io) and GitLab (registry.gitlab.com) container registry"
    license: "MIT"
    install: |
      bin.install "drprune"
release:
  github:
    owner: ci-monk
    name: drprune
  name_template: "v{{.Version}}"
