project_name: drprune
env:
  - GO111MODULE=on
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: drprune
    binary: drprune
    env:
      - CGO_ENABLED=0
    main: ./cmd/drprune/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64le
    mod_timestamp: '{{.CommitTimestamp}}'
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X "github.com/lpmatos/drprune/internal/version.builtDate={{.CommitDate}}"
      - -X "github.com/lpmatos/drprune/internal/version.builtBy=goreleaser"
      - -X "github.com/lpmatos/drprune/internal/version.cliVersion={{.Env.CLIENT_VERSION}}"
      - -X "github.com/lpmatos/drprune/internal/version.commit={{.Commit}}"
      - -X "github.com/lpmatos/drprune/internal/version.commitShort={{.ShortCommit}}"
      - -X "github.com/lpmatos/drprune/internal/version.commitBranch={{.Env.GIT_BRANCH}}"
      - -X "github.com/lpmatos/drprune/internal/version.goVersion={{.Env.GO_VERSION}}"
archives:
  - name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
snapshot:
  name_template: 'SNAPSHOT-{{ .Commit }}'
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256
changelog:
  skip: true
